services:
  frontend:
    image: ghcr.io/emmauopeople/1community-app-frontend:${FRONTEND_IMAGE_TAG}
    container_name: cameroonskills-frontend
    restart: unless-stopped
    expose:
      - "5173"

  backend:
    image: ghcr.io/emmauopeople/1community-app-backend:${BACKEND_IMAGE_TAG}
    container_name: cameroonskills-backend
    restart: unless-stopped
    env_file:
      - .env
      - .env.deploy
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: cameroonskills-nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot
    container_name: cameroonskills-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM;
      while :; do
      certbot renew --webroot -w /var/www/certbot --quiet;
      sleep 12h & wait $${!};
      done"
